name: 'Yarn Upgrader'
description: 'Run yarn upgrade'
branding:
  icon: chevrons-up
  color: purple
runs:
  using: "composite"
  steps: 
    - run: yarn
      shell: bash
    - run: yarn upgrade
      shell: bash
    - run: npx yarn-deduplicate yarn.lock
      shell: bash
